### ISSUE TITLE
Wellplate Selection

### ISSUE THREAD

**Issue by rahul-fakir** [biobotsdev/bioprint#1]
Upon start up, after homing all axis, and selecting a well-plate and clicking 'select well-plate' the extrudes move but not to their correct position. Usually stay in the same position with regards to X and Y axis.

**Comment by aidrusjames** [comment]
I am experiencing exactly the same problem as you with the Biobot1, since downloading the bioprint software, where upon selecting the well-plate, the extruders move up and down but do not move to the centre above the well plate.

**Comment by rsolorzano** [comment]
We have updated software that hasn't been pushed on github. email me at rsol@biobots.io and you can get the new link. 

Thanks
